In [2]:
import sqlite3
import pandas as pd

In [3]:
df = pd.read_csv("db/CHDB_data_city_all v6_0.csv")

C:\Users\irbyh\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
conn = sqlite3.connect('db/database.db')

In [7]:
df.to_sql(name='cities', con=conn)

C:\Users\irbyh\Anaconda3\lib\site-packages\pandas\core\generic.py:2130: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  dtype=dtype)

In [8]:
df1 = pd.read_sql_query("SELECT * FROM cities", conn)

In [9]:
df1

,index,state_abbr,state_fips,place_fips,stpl_fips,city_name,metric_name,group_name,metric_number,group_number,...,lci,uci,county_indicator,educ_indicator,multiplier_indicator,data_yr_type,geo_level,Date of export to MySQL database,version,NOTE - NCHS Disclaimer
0,0,HI,15,3,15003,Honolulu,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,The downloadable data tables shared on the Cit...
1,1,AL,1,7000,107000,Birmingham,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,None
2,2,AL,1,35896,135896,Hoover,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,None
3,3,AL,1,37000,137000,Huntsville,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,None
4,4,AL,1,50000,150000,Mobile,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,None
5,5,AL,1,51000,151000,Montgomery,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,None
6,6,AL,1,77256,177256,Tuscaloosa,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,None
7,7,AK,2,3000,203000,Anchorage,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,None
8,8,AZ,4,4720,404720,Avondale,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,None
9,9,AZ,4,12000,412000,Chandler,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,None
10,10,AZ,4,27400,427400,Gilbert,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,None
11,11,AZ,4,27820,427820,Glendale,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,None
12,12,AZ,4,46000,446000,Mesa,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,None
13,13,AZ,4,54050,454050,Peoria,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,None
14,14,AZ,4,55000,455000,Phoenix,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,None
15,15,AZ,4,65000,465000,Scottsdale,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,None
16,16,AZ,4,71510,471510,Surprise,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,None
17,17,AZ,4,73000,473000,Tempe,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,None
18,18,AZ,4,77000,477000,Tucson,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,None
19,19,AZ,4,85540,485540,Yuma,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,None
20,20,AR,5,23290,523290,Fayetteville,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,None
21,21,AR,5,24550,524550,Fort Smith,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,None
22,22,AR,5,35710,535710,Jonesboro,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,None
23,23,AR,5,41000,541000,Little Rock,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,None
24,24,AR,5,66080,566080,Springdale,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,None
25,25,CA,6,562,600562,Alameda,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,None
26,26,CA,6,884,600884,Alhambra,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,None
27,27,CA,6,2000,602000,Anaheim,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,None
28,28,CA,6,2252,602252,Antioch,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,None
29,29,CA,6,2364,602364,Apple Valley,Absenteeism,total population,1,1,...,-999.0,-999.0,-999.0,-999.0,-999.0,2015-2016,city,2019-06-11,6,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60470,60470,VA,51,156000,5156000,Newport News,Life expectancy,total population,37,1,...,76.4,76.7,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None
60471,60471,VA,51,157000,5157000,Norfolk,Life expectancy,total population,37,1,...,75.3,75.7,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None
60472,60472,VA,51,164000,5164000,Portsmouth,Life expectancy,total population,37,1,...,73.7,74.0,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None
60473,60473,VA,51,167000,5167000,Richmond,Life expectancy,total population,37,1,...,75.1,75.5,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None
60474,60474,VA,51,168000,5168000,Roanoke,Life expectancy,total population,37,1,...,75.0,75.1,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None
60475,60475,VA,51,176432,5176432,Suffolk,Life expectancy,total population,37,1,...,76.3,76.6,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None
60476,60476,VA,51,182000,5182000,Virginia Beach,Life expectancy,total population,37,1,...,78.3,78.7,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None
60477,60477,WA,53,303180,5303180,Auburn,Life expectancy,total population,37,1,...,78.7,78.9,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None
60478,60478,WA,53,305210,5305210,Bellevue,Life expectancy,total population,37,1,...,84.0,84.3,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None
60479,60479,WA,53,305280,5305280,Bellingham,Life expectancy,total population,37,1,...,80.9,81.1,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None
60480,60480,WA,53,322640,5322640,Everett,Life expectancy,total population,37,1,...,78.1,78.4,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None
60481,60481,WA,53,323515,5323515,Federal Way,Life expectancy,total population,37,1,...,79.2,79.4,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None
60482,60482,WA,53,335275,5335275,Kennewick,Life expectancy,total population,37,1,...,79.2,79.3,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None
60483,60483,WA,53,335415,5335415,Kent,Life expectancy,total population,37,1,...,79.7,79.9,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None
60484,60484,WA,53,357745,5357745,Renton,Life expectancy,total population,37,1,...,81.3,81.5,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None
60485,60485,WA,53,363000,5363000,Seattle,Life expectancy,total population,37,1,...,81.0,81.5,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None
60486,60486,WA,53,367000,5367000,Spokane,Life expectancy,total population,37,1,...,77.4,77.7,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None
60487,60487,WA,53,367167,5367167,Spokane Valley,Life expectancy,total population,37,1,...,77.7,77.9,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None
60488,60488,WA,53,370000,5370000,Tacoma,Life expectancy,total population,37,1,...,77.5,77.8,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None
60489,60489,WA,53,374060,5374060,Vancouver,Life expectancy,total population,37,1,...,78.4,78.7,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None
60490,60490,WA,53,380010,5380010,Yakima,Life expectancy,total population,37,1,...,78.1,78.2,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None
60491,60491,WV,54,414600,5414600,Charleston,Life expectancy,total population,37,1,...,75.8,76.0,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None
60492,60492,WI,55,502375,5502375,Appleton,Life expectancy,total population,37,1,...,NaN,NaN,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None
60493,60493,WI,55,531000,5531000,Green Bay,Life expectancy,total population,37,1,...,NaN,NaN,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None
60494,60494,WI,55,539225,5539225,Kenosha,Life expectancy,total population,37,1,...,NaN,NaN,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None
60495,60495,WI,55,548000,5548000,Madison,Life expectancy,total population,37,1,...,NaN,NaN,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None
60496,60496,WI,55,553000,5553000,Milwaukee,Life expectancy,total population,37,1,...,NaN,NaN,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None
60497,60497,WI,55,566000,5566000,Racine,Life expectancy,total population,37,1,...,NaN,NaN,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None
60498,60498,WI,55,584250,5584250,Waukesha,Life expectancy,total population,37,1,...,NaN,NaN,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None
60499,60499,WY,56,613900,5613900,Cheyenne,Life expectancy,total population,37,1,...,80.6,80.8,0.0,-999.0,-999.0,"2010-2015, 6 Year Modeled Estimate",city,2019-06-11,6,None